name: SSH Debug Runner (Upterm)

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Start SSH session
        uses: owenthereal/action-upterm@v1

      - name: Keep Runner Alive
        run: |
          echo "SSH session ready"
          while true; do
            sleep 60
          done
